<?php

$language = array
	(
	'title' => 'ACFUN 大 逃 杀',
	'index' => '首页',
	'fullwin' => '全屏模式',
	'backindex' => '返回首页',
	'game' => '游戏',
	'map' => '地图',
	'news' => '进行状况',
	'alive' => '当前幸存者',
	'winner' => '历史优胜者',
	'help' => '游戏帮助',
	'homepage' => '官方网站',
	'admin' => '游戏管理',
	'report' => '官方讨论区',
	'now' => '当前时刻',
	'gameinfo' => '游戏情报',
	'adminmsg' => '站长留言',
	'username' => '账号',
	'password' => '密码',
	'welcome' => '欢迎你，{$cuser}！',
	'login' => '登录',
	'numinfo' => '第 $gamenum 回游戏 ',
	'gamedate' => '{$month}月{$day}日 星期{$week["$wday"]} {$hour}:{$min}',
	'back' => '返回',
	'submit' => '提交',
	'reset' => '重设',
	'valid' => '入场手续',
	'validover' => '入场表格填写完成',
	'enternotice' => '进入会场',
	'enterbattlefield' => '进入ACFUN大逃杀战场',
	'gamestart' => '游戏开始',
	'enter' => '进入游戏',
	'quit' => '账号退出',
	'errormsg' => '出现错误',
	'name' => '姓名',
	'gender' => '分队',
	'icon' => '头像',
	'sNo' => '学号',
	'level' => '等级',
	'club' => '内定称号',
	'hp' => '生命',
	'sp' => '体力',
	'att' => '攻击力',
	'def' => '防御力',
	'combo' => '连斗',
	'exp' => '经验值',
	'weather' => '天气',
	'status' => '状态',
	'team' => '队伍',
	'inf' => '受伤部位',
	'pose' => '基础姿态',
	'tactic' => '应战策略',
	'kind1' => '种类',
	'rage' => '怒气',
	'killnum' => '击杀数',
	'money' => '金钱',
	'equip' => '装备',
	'pack' => '包裹',
	'startpack' => '随机道具',
	'skill' => '熟',
	'command' => '指令',
	'wep' => '武器',
	'arb' => '防具',
	'effect' => '攻击',
	'cmd_choice' => '你想要做什么？',
	'chat' => '消息',
	'moneyunit' => '元',
	'wp' => '殴',
	'wk' => '斩',
	'wg' => '射',
	'wc' => '投',
	'wd' => '爆',
	'wf' => '灵',
	'newsnotice' => '<span class="evergreen">“各位仍在努力奋战，咱很欣慰。<br />以下是到现在为止的游戏状况。<br />请各位再接再厉。”</span>',
	'useitem' => '使用',
	'end' => '游戏结束！',
	'send' => '发送',
	'refresh' => '刷新',
	'maptitle' => '会场简易地图',
	);


?>