-- ;
-- 表的结构 `bra_players` ;
-- 储存角色数据的激活信息，包括PC和NPC。 ;
-- ;

DROP TABLE IF EXISTS bra_players;
CREATE TABLE bra_players (
  pid smallint unsigned NOT NULL auto_increment,
  type tinyint unsigned NOT NULL default '0',
  name char(15) NOT NULL default '',
  pass char(32) NOT NULL default '',
  company smallint NOT NULL default '0', 
  gd char(1) NOT NULL default 'm',
  sNo smallint unsigned NOT NULL default '0',
  icon tinyint unsigned NOT NULL default '0',
  club tinyint unsigned NOT NULL default '0',
  gamehonour char(4) NOT NULL default '',
  gainhonour varchar(20) NOT NULL default '',
  technique varchar(30) NOT NULL default '',
  techlevel tinyint unsigned NOT NULL default '0',
  story tinyint unsigned NOT NULL default '0',
  lastcmd int(10) unsigned NOT NULL default '0',
  lasteff int(10) unsigned NOT NULL default '0',
  laststn int(10) unsigned NOT NULL default '0',
  lastslp int(10) unsigned NOT NULL default '0',
  cdmsec smallint(3) unsigned NOT NULL default '0',
  cdtime mediumint unsigned NOT NULL default '0',
  hp smallint unsigned NOT NULL default '0',
  mhp smallint unsigned NOT NULL default '0',
  sp smallint unsigned NOT NULL default '0',
  msp smallint unsigned NOT NULL default '0',
  att smallint unsigned NOT NULL default '0',
  def smallint unsigned NOT NULL default '0',
  pls tinyint unsigned NOT NULL default '0',
  lvl tinyint unsigned NOT NULL default '0',
  `exp` smallint unsigned NOT NULL default '0',
  money smallint unsigned NOT NULL default '0',
  bid smallint unsigned NOT NULL default '0',
  `inf` varchar(10) NOT NULL default '',
  rage tinyint unsigned NOT NULL default '0',
  pose tinyint(1) unsigned NOT NULL default '0',
  tactic tinyint(1) unsigned NOT NULL default '0',
  killnum smallint unsigned NOT NULL default '0',
  state tinyint unsigned NOT NULL default '0',
  `wp` smallint unsigned NOT NULL default '0',
  `wk` smallint unsigned NOT NULL default '0',
  `wg` smallint unsigned NOT NULL default '0',
  `wc` smallint unsigned NOT NULL default '0',
  `wd` smallint unsigned NOT NULL default '0',
  `wf` smallint unsigned NOT NULL default '0',
  `teamID` varchar(15) NOT NULL default '',
  `teamPass` varchar(15) NOT NULL default '',
  wep varchar(30) NOT NULL default '',
  wepk char(5) NOT NULL default '',
  wepe smallint unsigned NOT NULL default '0',
  weps char(5) NOT NULL default '0',
  wepsk varchar(30) NOT NULL default '',
  wepnp smallint unsigned NOT NULL default '0',
  arb varchar(30) NOT NULL default '',
  arbk char(5) NOT NULL default '',
  arbe smallint unsigned NOT NULL default '0',
  arbs char(5) NOT NULL default '0',
  arbsk varchar(30) NOT NULL default '',
  arbnp smallint unsigned NOT NULL default '0',
  arh varchar(30) NOT NULL default '',
  arhk char(5) NOT NULL default '',
  arhe smallint unsigned NOT NULL default '0',
  arhs char(5) NOT NULL default '0',
  arhsk varchar(30) NOT NULL default '',
  arhnp smallint unsigned NOT NULL default '0',
  ara varchar(30) NOT NULL default '',
  arak char(5) NOT NULL default '',
  arae smallint unsigned NOT NULL default '0',
  aras char(5) NOT NULL default '0',
  arask varchar(30) NOT NULL default '',
  aranp smallint unsigned NOT NULL default '0',
  arf varchar(30) NOT NULL default '',
  arfk char(5) NOT NULL default '',
  arfe smallint unsigned NOT NULL default '0',
  arfs char(5) NOT NULL default '0',
  arfsk varchar(30) NOT NULL default '',
  arfnp smallint unsigned NOT NULL default '0',
  art varchar(30) NOT NULL default '',
  artk char(5) NOT NULL default '',
  arte smallint unsigned NOT NULL default '0',
  arts char(5) NOT NULL default '0',
  artsk varchar(30) NOT NULL default '',
  artnp smallint unsigned NOT NULL default '0',
  itm0 varchar(30) NOT NULL default '',
  itmk0 char(5) NOT NULL default '',
  itme0 smallint unsigned NOT NULL default '0',
  itms0 char(5) NOT NULL default '0',
  itmsk0 varchar(30) NOT NULL default '',
  itmnp0 smallint unsigned NOT NULL default '0',
  itm1 varchar(30) NOT NULL default '',
  itmk1 char(5) NOT NULL default '',
  itme1 smallint unsigned NOT NULL default '0',
  itms1 char(5) NOT NULL default '0',
  itmsk1 varchar(30) NOT NULL default '',
  itmnp1 smallint unsigned NOT NULL default '0',
  itm2 varchar(30) NOT NULL default '',
  itmk2 char(5) NOT NULL default '',
  itme2 smallint unsigned NOT NULL default '0',
  itms2 char(5) NOT NULL default '0',
  itmsk2 varchar(30) NOT NULL default '',
  itmnp2 smallint unsigned NOT NULL default '0',
  itm3 varchar(30) NOT NULL default '',
  itmk3 char(5) NOT NULL default '',
  itme3 smallint unsigned NOT NULL default '0',
  itms3 char(5) NOT NULL default '0',
  itmsk3 varchar(30) NOT NULL default '',
  itmnp3 smallint unsigned NOT NULL default '0',
  itm4 varchar(30) NOT NULL default '',
  itmk4 char(5) NOT NULL default '',
  itme4 smallint unsigned NOT NULL default '0',
  itms4 char(5) NOT NULL default '0',
  itmsk4 varchar(30) NOT NULL default '',
  itmnp4 smallint unsigned NOT NULL default '0',
  itm5 varchar(30) NOT NULL default '',
  itmk5 char(5) NOT NULL default '',
  itme5 smallint unsigned NOT NULL default '0',
  itms5 char(5) NOT NULL default '0',
  itmsk5 varchar(30) NOT NULL default '',
  itmnp5 smallint unsigned NOT NULL default '0',
  itm6 varchar(30) NOT NULL default '',
  itmk6 char(5) NOT NULL default '',
  itme6 smallint unsigned NOT NULL default '0',
  itms6 char(5) NOT NULL default '0',
  itmsk6 varchar(30) NOT NULL default '',
  itmnp6 smallint unsigned NOT NULL default '0',

  PRIMARY KEY  (pid),
  INDEX TYPE (type, sNo),
  INDEX NAME (name, type)
	
) ENGINE=MyISAM;



