<?php

$language = array
	(
	'title' => '莱 卡 大 逃 杀',
	
	'index' => '首页',
	'fullwin' => '全屏模式',
	'backindex' => '返回首页',
	
	'user' => '帐号资料',
	'register' => '账号注册',
	'game' => '进入游戏',
	'map' => '战场地图',
	'news' => '进行状况',
	'alive' => '当前幸存',
	'winner' => '历史优胜',
	'rank' => '玩家排行',
	'help' => '游戏帮助',
	'homepage' => '官方网站',
	'admin' => '游戏管理',
	
	'now' => '当前时刻',
	'gameinfo' => '游戏情报',
	'adminmsg' => '站长留言',
	'username' => '账号',
	'password' => '密码',
	'welcome' => '欢迎你，{$cuser}！',
	'login' => '登录',
	'numinfo' => '第 $gamenum 回游戏 ',
	'gamedate' => '{$month}月{$day}日 星期{$week["$wday"]} {$hour}:{$min}',
	'back' => '返回',
	'submit' => '提交',
	'reset' => '重设',
	'ok' => '确定',
	
	'basicdata' => '账户基本资料',
	'advanceddata' => '账户个性化资料',
	'opass' => '原密码',
	'npass' => '新密码',
	'rnpass' => '重复新密码',
	'cannotedit' => '此处无法修改',
	'motto' => '游戏签名',
	'criticalmsg' => '必杀台词',
	'killmsg' => '杀人宣言',
	'lastword' => '遗言',
	'username_comment' => '最长15个英文字符或者汉字，不能出现半角符号',
	'password_comment' => '最长24个字符，留空为不修改',
	'motto_comment' => '写下彰显个性的台词，120个字以内。<br />可用BBcode标签：[br]	[b]	[i]	[u]	[strike]	[red]	[yellow]	[lime]	[green]	[blue]	[aqua]',
	'criticalmsg_comment' => '写下你使出重击或必杀技时的台词，60个字以内',
	'killmsg_comment' => '写下你杀死对手的留言，60个字以内',
	'lastword_comment' => '写下你不幸被害时的台词，60个字以内',
	'credits' => '游戏积分',
	'validtimes' => '游戏次数',
	'lastgame' => '最近局',
//	'killnum' => '杀人总数',
	'honour' => '称号',
	'select_honour' => '选择游戏称号',
	'nohonour' => '无称号',
	
	'valid' => '入场手续',
	'validover' => '入场表格填写完成',
	'enternotice' => '进入会场',
	'enterbattlefield' => '进入大逃杀战场',
	'gamestart' => '游戏开始',
	'enter' => '进入游戏',
	'quit' => '账号退出',
	'errormsg' => '出现错误',
	
	'name' => '姓名',
	'gender' => '性别',
	'icon' => '头像',
	'sNo' => '学号',
	'company' => '同伴',
	'level' => '等级',
	'pls' => '位置',
	'club' => '内定称号',
	'hp' => '生命',
	'sp' => '体力',
	'att' => '攻击力',
	'def' => '防御力',
	'combo' => '连斗',
	'duel' => '死斗',
	'exp' => '经验值',
	'weather' => '天气',
	'status' => '状态',
	'team' => '队伍',
	'inf' => '受伤部位',
	'pose' => '基础姿态',
	'tactic' => '应战策略',
	'kind1' => '种类',
	'rage' => '怒气',
	'killnum' => '击杀数',
	'money' => '金钱',
	'technique' => '技能',
	'equip' => '装备',
	'pack' => '包裹',
	'itmsk' => '属性',
	'startpack' => '随机道具',
	'skill' => '熟',
	'command' => '指令',
	'wep' => '武器',
	'arb' => '身体防具',
	'arh' => '头部防具',
	'ara' => '腕部防具',
	'arf' => '足部防具',
	'art' => '饰品',
	'effect' => '攻击',
	'escape' => '逃跑',
	'cmd_choice' => '你想要做什么？',
	'chat' => '消息',
	'moneyunit' => '元',
	'wp' => '殴',
	'wk' => '斩',
	'wg' => '射',
	'wc' => '投',
	'wd' => '爆',
	'wf' => '灵',
	'newsnotice' => '<div style="float:left;"><img border="0" src="img/n_7.gif"></div><div class="linen">“以下是到现在为止的游戏状况。<br />各位参战者请加油哦！”</div>',
	'newsnotice2' => '<div style="float:left;"><img border="0" src="img/question.gif"></div><div class="linen">“………………”</div>',
	'useitem' => '使用',
	'end' => '游戏结束！',
	'send' => '发送',
	'refresh' => '刷新',
	'maptitle' => '虚拟世界地图',
	'itemmenu' => '道具',
	'packmenu' => '包裹',
	'restmenu' => '修整',
	'spmenu' => '特殊',
	'teammenu' => '队伍',
	'cpmenu' => '同伴',
	'search' => '探索',
	'itemget' => '拾取道具',
	'itemoff' => '卸下装备',
	'itemdrop' => '丢弃道具',
	'itemmerge' => '整理包裹',
	'itemmix' => '合成道具',
	'switch' => '切换角色',
	'quitshop' => '退出商店',
	'backtolist' => '返回列表',
	);


?>