--
-- 表的结构 `bra_users`
-- 储存用户的激活信息
--

DROP TABLE IF EXISTS bra_users;
CREATE TABLE bra_users (
  uid mediumint(8) unsigned NOT NULL auto_increment,
  username char(15) NOT NULL default '',
  `password` char(32) NOT NULL default '',
  groupid tinyint unsigned NOT NULL default '0',
  lastgame smallint unsigned NOT NULL default '0',
  ip char(15) NOT NULL default '',
  credits int(10) NOT NULL default '0',
  validtimes smallint unsigned NOT NULL default '0',
  wintimes smallint unsigned NOT NULL default '0',
  honour varchar(30) NOT NULL default '',
  gender char(1) NOT NULL default 'n',
  icon tinyint unsigned NOT NULL default '0',
  motto varchar(120) NOT NULL default '',
  criticalmsg varchar(60) NOT NULL default '',
  killmsg varchar(60) NOT NULL default '',
  lastword varchar(60) NOT NULL default '',

  PRIMARY KEY  (uid),
  UNIQUE KEY username (username)

) TYPE=MyISAM;

--
-- 插入初始数据 `bra_users`
--


--
-- 表的结构 `bra_winners`
-- 储存每局获胜者的信息
--

DROP TABLE IF EXISTS bra_winners;
CREATE TABLE bra_winners (
  gid smallint unsigned NOT NULL default '0',
  name char(15) NOT NULL default '',
  gamehonour char(4) NOT NULL default '',
  gainhonour varchar(20) NOT NULL default '',
  pass char(32) NOT NULL default '',
  gd char(1) NOT NULL default 'm',
  sNo smallint unsigned NOT NULL default '0',
  icon tinyint unsigned NOT NULL default '0',
  club tinyint unsigned NOT NULL default '0',
  technique varchar(30) NOT NULL default '',
  hp smallint unsigned NOT NULL default '0',
  mhp smallint unsigned NOT NULL default '0',
  sp smallint unsigned NOT NULL default '0',
  msp smallint unsigned NOT NULL default '0',
  att smallint unsigned NOT NULL default '0',
  def smallint unsigned NOT NULL default '0',
  pls tinyint unsigned NOT NULL default '0',
  lvl tinyint unsigned NOT NULL default '0',
  `exp` smallint unsigned NOT NULL default '0',
  money smallint unsigned NOT NULL default '0',
  `inf` varchar(10) not null default '',
  rage tinyint unsigned NOT NULL default '0',
  pose tinyint(1) unsigned NOT NULL default '0',
  tactic tinyint(1) unsigned NOT NULL default '0',
  killnum smallint unsigned NOT NULL default '0',
  `wp` smallint unsigned not null default '0',
  `wk` smallint unsigned not null default '0',
  `wg` smallint unsigned not null default '0',
  `wc` smallint unsigned not null default '0',
  `wd` smallint unsigned not null default '0',
  `wf` smallint unsigned not null default '0',
  `teamID` varchar(15) not null default '',
  `teamPass` varchar(15) NOT NULL default '',
  wep varchar(30) NOT NULL default '',
  wepk char(5) NOT NULL default '',
  wepe smallint unsigned NOT NULL default '0',
  weps char(5) NOT NULL default '0',
  wepsk varchar(30) NOT NULL default '',
  wepnp smallint unsigned NOT NULL default '0',
  arb varchar(30) NOT NULL default '',
  arbk char(5) NOT NULL default '',
  arbe smallint unsigned NOT NULL default '0',
  arbs char(5) NOT NULL default '0',
  arbsk varchar(30) NOT NULL default '',
  arbnp smallint unsigned NOT NULL default '0',
  arh varchar(30) NOT NULL default '',
  arhk char(5) NOT NULL default '',
  arhe smallint unsigned NOT NULL default '0',
  arhs char(5) NOT NULL default '0',
  arhsk varchar(30) NOT NULL default '',
  arhnp smallint unsigned NOT NULL default '0',
  ara varchar(30) NOT NULL default '',
  arak char(5) NOT NULL default '',
  arae smallint unsigned NOT NULL default '0',
  aras char(5) NOT NULL default '0',
  arask varchar(30) NOT NULL default '',
  aranp smallint unsigned NOT NULL default '0',
  arf varchar(30) NOT NULL default '',
  arfk char(5) NOT NULL default '',
  arfe smallint unsigned NOT NULL default '0',
  arfs char(5) NOT NULL default '0',
  arfsk varchar(30) NOT NULL default '',
  arfnp smallint unsigned NOT NULL default '0',
  art varchar(30) NOT NULL default '',
  artk char(5) NOT NULL default '',
  arte smallint unsigned NOT NULL default '0',
  arts char(5) NOT NULL default '0',
  artsk varchar(30) NOT NULL default '',
  artnp smallint unsigned NOT NULL default '0',
  itm0 varchar(30) NOT NULL default '',
  itmk0 char(5) NOT NULL default '',
  itme0 smallint unsigned NOT NULL default '0',
  itms0 char(5) NOT NULL default '0',
  itmsk0 varchar(30) NOT NULL default '',
  itmnp0 smallint unsigned NOT NULL default '0',
  itm1 varchar(30) NOT NULL default '',
  itmk1 char(5) NOT NULL default '',
  itme1 smallint unsigned NOT NULL default '0',
  itms1 char(5) NOT NULL default '0',
  itmsk1 varchar(30) NOT NULL default '',
  itmnp1 smallint unsigned NOT NULL default '0',
  itm2 varchar(30) NOT NULL default '',
  itmk2 char(5) NOT NULL default '',
  itme2 smallint unsigned NOT NULL default '0',
  itms2 char(5) NOT NULL default '0',
  itmsk2 varchar(30) NOT NULL default '',
  itmnp2 smallint unsigned NOT NULL default '0',
  itm3 varchar(30) NOT NULL default '',
  itmk3 char(5) NOT NULL default '',
  itme3 smallint unsigned NOT NULL default '0',
  itms3 char(5) NOT NULL default '0',
  itmsk3 varchar(30) NOT NULL default '',
  itmnp3 smallint unsigned NOT NULL default '0',
  itm4 varchar(30) NOT NULL default '',
  itmk4 char(5) NOT NULL default '',
  itme4 smallint unsigned NOT NULL default '0',
  itms4 char(5) NOT NULL default '0',
  itmsk4 varchar(30) NOT NULL default '',
  itmnp4 smallint unsigned NOT NULL default '0',
  itm5 varchar(30) NOT NULL default '',
  itmk5 char(5) NOT NULL default '',
  itme5 smallint unsigned NOT NULL default '0',
  itms5 char(5) NOT NULL default '0',
  itmsk5 varchar(30) NOT NULL default '',
  itmnp5 smallint unsigned NOT NULL default '0',
  itm6 varchar(30) NOT NULL default '',
  itmk6 char(5) NOT NULL default '',
  itme6 smallint unsigned NOT NULL default '0',
  itms6 char(5) NOT NULL default '0',
  itmsk6 varchar(30) NOT NULL default '',
  itmnp6 smallint unsigned NOT NULL default '0',
  motto varchar(120) NOT NULL default '',
  wmode tinyint unsigned NOT NULL default '0',
  vnum smallint unsigned NOT NULL default '0',
  gtime int(10) unsigned NOT NULL default '0',
  gstime int(10) unsigned NOT NULL default '0',
  getime int(10) unsigned NOT NULL default '0',
  hdmg int unsigned NOT NULL default '0',
  hdp char(15) NOT NULL default '',
  hkill smallint unsigned NOT NULL default '0',
  hkp char(15) NOT NULL default '',

  UNIQUE KEY (gid)
) TYPE=MyISAM;